build_script: set PATH=%PATH%;%WIX% && mvn package
artifacts:
  - path: target\*.msi
    name: Windows Installer

# The unit-tests are run as part of the mvn package build script, so we only need to test the installation here
test_script:
  - for %%x in (target\*.msi) do msiexec.exe /a "%%x"